version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance-frontend-1
    restart: always
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - /app/node_modules
